apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginxtest
  namespace: nginxtest
spec:
  releaseName: nginxtest
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
  interval: 50m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
  # values:
  #   redis:
  #     enabled: true
  #     repository: public.ecr.aws/docker/library/redis
  #     tag: 7.0.6
  #   ingress:
  #     enabled: true
  #     className: nginx
